version: '3.8'

services:
  # MySQL Database (Development)
  mysql-dev:
    image: mysql:8.0
    container_name: taskflow-mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: task_management_dev
      MYSQL_USER: taskflow
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./scripts/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - taskflow-dev-network

  # MongoDB Database (Development)
  mongodb-dev:
    image: mongo:7.0
    container_name: taskflow-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: task_management_dev
    ports:
      - "27018:27017"
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - taskflow-dev-network

  # Backend API (Development)
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: dev
    container_name: taskflow-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      JWT_SECRET: dev_jwt_secret_key
      JWT_EXPIRES_IN: 7d
      MYSQL_HOST: mysql-dev
      MYSQL_PORT: 3306
      MYSQL_USER: taskflow
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: task_management_dev
      MONGODB_URI: mongodb://admin:password@mongodb-dev:27017/task_management_dev?authSource=admin
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5001:5000"
    depends_on:
      - mysql-dev
      - mongodb-dev
    networks:
      - taskflow-dev-network
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs

  # Frontend Application (Development)
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: dev
    container_name: taskflow-frontend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:5001/api
    ports:
      - "3001:3000"
    depends_on:
      - backend-dev
    networks:
      - taskflow-dev-network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  # Redis (Development)
  redis-dev:
    image: redis:7-alpine
    container_name: taskflow-redis-dev
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - taskflow-dev-network

volumes:
  mysql_dev_data:
    driver: local
  mongodb_dev_data:
    driver: local

networks:
  taskflow-dev-network:
    driver: bridge
